### ISSUE TITLE
Dependency on babel-polyfill

### ISSUE THREAD

**Issue by dodas** [slventures/googlemaps-js-rich-marker#6]
Hello, it looks like your fork is dependant on Array.prototype.values, so you need to polyfill it. Could you add `require("babel-polyfill")` to start of your module, please?

**Comment by OOPMan** [comment]
@dodas Will do so :-)

**Comment by OOPMan** [comment]
@dodas On second look, I'm not even sure why that is using `Array.prototype.values`, since `for...of` can iterate over `Array`s directly.

**Comment by dodas** [comment]
Yeah, I wasn't sure why it's there too. Tried now, works OK without it.

**Comment by OOPMan** [comment]
@dodas Probably some code I wrote in a rush. That `memoize` function is also bugged, albeit in a harmless fashion.

**Comment by OOPMan** [comment]
@dodas After some consideration I'm not going to directly add a `require("babel-polyfill")` to the code for two reasons:
1. It would explicitly force users to transpile with Babel, as opposed to allowing usage with other transpilation platforms.
2. Eventually, ES6 and ES6 modules will (hopefully) be supported directly by all active runtime environments and thus a dependency on a polyfill will be unnecessary.

What I will do, however, is add a note in the README.md file detailing that a transpilation environment and ES6 polyfill will be necessary for usage in non-compliant environments.

Is that okay?

**Comment by jcwkroeze** [comment]
Addressed by #7
